name: addHosts
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 10 * * * *

jobs:
  GenerateHostsFile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        sudo rm -rf /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        sudo apt-get install -y dos2unix
        bash update_action.sh
    - name: Commit files
      run: |
        git pull
        git config --local user.email ${{ secrets.MYEMAIL }}
        git config --local user.name ${{ secrets.MYUSERNAME }}
        git commit -m "Update Hosts" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
